name: GitHub Actions Demo
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: gradlew change permission
        run: chmod +x ./gradlew
      - name: build project [release apk]
        run: ./gradlew assembleRelease
      - name: get firebase service account key & google services
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' > './app/sa_key.json'
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > './app/google-services.json'
      - name: firebase upload
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: ./app/sa_key.json
          groups: testers
          file: app/build/outputs/apk/release/app-release-unsigned.apk
